"""Framework-free per-dtag PanDDA2 hit-identification processing.

This is the standalone equivalent of the body of
``dlstbx.wrapper.pandda_xchem.PanDDAWrapper.run`` for a single dataset, with
the zocalo / ispyb coupling removed. It takes plain paths and a logger, reuses
the low-level helpers in :mod:`dlstbx.util.pandda` and the MVS output helpers,
and returns ``True`` on success.
"""

from __future__ import annotations

import json
import logging
import shutil
import subprocess
from pathlib import Path

import gemmi
import yaml

from dlstbx.cli.pandda_array import PANDDA_2_DIR
from dlstbx.util.mvs.helpers import find_residue_by_name
from dlstbx.util.pandda import (
    get_contact_chain,
    map_sigma,
    mask_map,
    merge_build,
    read_pandda_map,
    remove_nearby_atoms,
    remove_waters_from_ligand,
    save_xmap,
)


def process_pandda_dataset(
    *,
    model_dir: Path,
    panddas_dir: Path,
    dtag: str,
    pandda_args: str = "",
    timeout_minutes: float = 145,
    overwrite: bool = False,
    pandda2_dir: str = PANDDA_2_DIR,
    logger: logging.Logger,
) -> bool:
    """Run PanDDA2 -> Rhofit -> ligand scoring -> merge -> output for one dtag.

    Args:
        model_dir: the shared ``model_building`` directory; ``model_dir/<dtag>``
            must already contain ``compound/<code>.smiles`` and, for Rhofit,
            ``compound/<code>.cif`` (restraints generated by an upstream job).
        panddas_dir: PanDDA2 output directory (``.../pandda2/panddas``).
        dtag: dataset tag (the per-crystal directory name).
        pandda_args: extra ``--key=value`` args forwarded to PanDDA2's
            ``process_dataset.py`` (e.g. from ``.user.yaml``).
        timeout_minutes: wall-clock timeout for the PanDDA2 step.
        overwrite: if set, delete any existing ``processed_datasets/<dtag>``
            before running.
        pandda2_dir: PanDDA2 software install root.
        logger: where to send progress/error messages.

    Returns:
        ``True`` if a pandda model was produced, ``False`` otherwise.
    """
    panddas_dir.mkdir(parents=True, exist_ok=True)
    dataset_dir = model_dir / dtag
    compound_dir = dataset_dir / "compound"

    logger.info(f"Processing dtag: {dtag}")

    smiles_files = list(compound_dir.glob("*.smiles"))

    if len(smiles_files) == 0:
        logger.error(
            f"No .smiles file present in {compound_dir}, cannot continue for dtag {dtag}"
        )
        return False
    elif len(smiles_files) > 1:
        logger.error(
            f"Multiple .smiles files found in {compound_dir}: {smiles_files}, warning for dtag {dtag}"
        )
        return False

    smiles_file = smiles_files[0]
    CompoundCode = smiles_file.stem
    smiles = smiles_file.read_text().strip()

    # Restraints generated upstream by the ligand-restraints job
    ligand_cif = compound_dir / f"{CompoundCode}.cif"
    attachments = []

    # -------------------------------------------------------
    # PanDDA2

    dataset_pdir = panddas_dir / "processed_datasets" / dtag
    pandda2_log = dataset_pdir / "pandda2.log"
    attachments.extend([pandda2_log, ligand_cif])

    if overwrite and dataset_pdir.exists():
        shutil.rmtree(dataset_pdir)

    pandda2_command = f"source {pandda2_dir}/venv/bin/activate; \
    python -u {pandda2_dir}/scripts/process_dataset.py --data_dirs={model_dir} --out_dir={panddas_dir} --dtag={dtag} --use_ligand_data=True --local_cpus=4 {pandda_args}"

    logger.info(f"Running PanDDA2 command: {pandda2_command}")

    try:
        result = subprocess.run(
            pandda2_command,
            shell=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            cwd=dataset_dir,
            check=True,
            timeout=timeout_minutes * 60,
        )

    except subprocess.CalledProcessError as e:
        logger.error(f"PanDDA2 command: '{pandda2_command}' failed")
        logger.info(e.stdout)
        pandda2_log.parent.mkdir(parents=True, exist_ok=True)
        with open(pandda2_log, "w") as log_file:
            log_file.write(e.stdout or "")
        return False

    pandda2_log.parent.mkdir(parents=True, exist_ok=True)
    with open(pandda2_log, "w") as log_file:
        log_file.write(result.stdout)

    # -------------------------------------------------------
    # PanDDA Rhofit ligand fitting

    ligand_dir = dataset_pdir / "ligand_files"
    ligand_dir.mkdir(exist_ok=True)

    # pandda2 not moving files into ligand_dir fix
    for file in compound_dir.rglob("*"):
        if file.is_file() and file.suffix.lower() in {".pdb", ".cif", ".smiles"}:
            targets = [ligand_dir / file.name, dataset_dir / file.name]
            for target in targets:
                if target.exists() or target.is_symlink():
                    target.unlink()
                target.symlink_to(file)

    modelled_dir = dataset_pdir / "modelled_structures"
    out_dir = modelled_dir / "rhofit"
    out_dir.mkdir(parents=True, exist_ok=True)
    events_yaml = dataset_pdir / "events.yaml"

    if not events_yaml.exists():
        logger.info(f"{events_yaml} does not exist, can't continue...")
        return False

    with open(events_yaml, "r") as fh:
        data = yaml.load(fh, Loader=yaml.SafeLoader)

    if not data:
        logger.info(f"No events in {events_yaml}, can't continue...")
        return False

    # Determine which builds to perform. More than one binder is unlikely and score
    # ranks well so build the best scoring event of each dataset.
    best_key = max(data, key=lambda k: data[k]["Score"])
    best_entry = data[best_key]

    event_idx = best_key
    event_score = best_entry["Score"]
    event_coord = best_entry["Centroid"]

    restricted_build_dmap = dataset_pdir / "build.ccp4"
    z_map = dataset_pdir / f"{dtag}-z_map.native.ccp4"
    event_map = next(dataset_pdir.glob(f"{dtag}-event_{event_idx}_1-BDC_*"), None)
    pdb_file = dataset_pdir / f"{dtag}-pandda-input.pdb"
    mtz_file = dataset_pdir / f"{dtag}-pandda-input.mtz"
    restricted_pdb_file = dataset_pdir / "build.pdb"

    if event_map is None:
        logger.error(f"No event map found for {dtag} event {event_idx}, can't continue")
        return False

    # Rhofit can be confused by hunting non-binding site density. This can be
    # avoided by truncating the map to near the binding site
    dmap = read_pandda_map(event_map)
    dmap = mask_map(dmap, event_coord)
    save_xmap(dmap, restricted_build_dmap)

    # Rhofit masks the protein before building. If the original protein model
    # clips the event then this results in autobuilding becoming impossible.
    remove_nearby_atoms(pdb_file, event_coord, 10.0, restricted_pdb_file)

    cifs = list(ligand_dir.glob("*.cif"))
    if not cifs:
        logger.error(
            f"No ligand .cif in {ligand_dir} for {dtag}, cannot run Rhofit (restraints missing?)"
        )
        return False
    cut = map_sigma(restricted_build_dmap)

    rhofit_log = dataset_pdir / "rhofit.log"
    attachments.extend([event_map, z_map, rhofit_log])
    rhofit_command = f"module load buster; source {pandda2_dir}/venv/bin/activate; \
    {pandda2_dir}/scripts/pandda_rhofit.sh -pdb {restricted_pdb_file} -map {restricted_build_dmap} -mtz {mtz_file} -cif {cifs[0]} -out {out_dir} -cut {cut} > {rhofit_log};"

    logger.info(f"Running PanDDA Rhofit command: {rhofit_command}")

    try:
        subprocess.run(
            rhofit_command,
            shell=True,
            capture_output=True,
            text=True,
            cwd=panddas_dir,
            check=True,
            timeout=60 * 60,
        )

    except subprocess.CalledProcessError as e:
        logger.error(f"Rhofit command: '{rhofit_command}' failed")
        logger.info(e.stdout)
        logger.error(e.stderr)

    # -------------------------------------------------------
    # Ligand scoring
    build_scores = {}
    build_dir = out_dir / "rhofit"
    rhofit_builds = list(build_dir.glob("Hit*.pdb"))

    # Include any PanDDA2 internal autobuilds
    pandda2_build = next(
        dataset_pdir.glob(f"*_event_{best_key}_best_autobuild.pdb"), None
    )
    if pandda2_build:
        build_scores[pandda2_build] = event_score

    if not pandda2_build and not rhofit_builds:
        logger.info(f"No autobuilds for {dtag}, can't continue")
        return False

    logger.info(f"Running Ligand Score routine for {build_dir}")

    # Iterate over rhofit builds and score each one
    for build_path in rhofit_builds:
        ligand_score = build_dir / f"{build_path.stem}.txt"

        st = gemmi.read_structure(str(build_path))
        chain, res = find_residue_by_name(st, "LIG")
        ligand_id = chain.name + f"/{res.seqid.num}"

        score_command = f"source {pandda2_dir}/venv/bin/activate; \
        python {pandda2_dir}/scripts/ligand_score.py --mtz_path={mtz_file} --zmap_path={z_map} --ligand_id={ligand_id} --structure_path={build_path} --out_path={ligand_score}"

        try:
            subprocess.run(score_command, shell=True, check=True)
        except subprocess.CalledProcessError as e:
            logger.error(f"Ligand score command: '{score_command}' failed: {e}")
            continue

        with open(ligand_score, "r") as fh:
            build_scores[build_path] = float(fh.read().strip())

    if not build_scores:
        logger.info(f"No scored autobuilds for {dtag}, can't continue")
        return False

    best_build_path = max(build_scores, key=lambda _x: build_scores[_x])
    best_score = build_scores[best_build_path]

    logger.info(f"Best ligand score for {dtag} = {best_score}: {best_build_path}")

    # Persist the best score so a downstream collate can bucket datasets by score
    (dataset_pdir / "best_score.txt").write_text(str(best_score))

    # -------------------------------------------------------
    # Merge the protein structure with best fitted ligand -> pandda model

    protein_st_file = dataset_pdir / f"{dtag}-pandda-input.pdb"
    ligand_st_file = best_build_path
    pandda_model = modelled_dir / f"{dtag}-pandda-model.pdb"
    attachments.extend([pandda_model])

    protein_st = gemmi.read_structure(str(protein_st_file))
    ligand_st = gemmi.read_structure(str(ligand_st_file))
    contact_chain = get_contact_chain(protein_st, ligand_st)
    merge_build(protein_st, ligand_st, contact_chain)

    if pandda_model.exists():  # backup previous model
        shutil.copy2(pandda_model, modelled_dir / "pandda-internal-fitted.pdb")

    protein_st.write_pdb(str(pandda_model))

    try:
        remove_waters_from_ligand(pandda_model, logger)
    except Exception as e:
        logger.error(f"Exception removing waters from {pandda_model}: {e}")

    # -------------------------------------------------------
    # Output

    # try:
    #     cropped_event_map = save_cropped_map(
    #         str(pandda_model), str(event_map), "LIG", radius=6
    #     )
    #     cropped_z_map = save_cropped_map(str(pandda_model), str(z_map), "LIG", radius=6)
    #     mvs_html = gen_html_pandda(
    #         str(pandda_model),
    #         cropped_event_map,
    #         cropped_z_map,
    #         resname="LIG",
    #         outdir=dataset_pdir,
    #         dtag=dtag,
    #         smiles=smiles,
    #         score=best_score,
    #     )
    #     attachments.extend([mvs_html])
    # except Exception as e:
    #     logger.debug(f"Exception generating mvs html: {e}")

    results = [
        ["SMILES code", "Best autobuild", "Ligand score"],
        [f"{smiles}", f"{best_build_path}", f"{best_score}"],
    ]
    json_results = dataset_pdir / "pandda2_results.json"
    with open(json_results, "w") as f:
        json.dump(results, f)
    attachments.extend([json_results])

    produced = [str(f) for f in attachments if f and Path(f).exists()]
    logger.info(f"Produced files for {dtag}: {produced}")

    logger.info(f"PanDDA2 pipeline finished successfully for dtag {dtag}")
    return True
