#!/bin/bash
#
# LIBTBX_SET_DISPATCHER_NAME dials.swirly_window

if [[ `uname -s` == 'Darwin' ]]; then
    open $(libtbx.find_in_repositories dlstbx/scratch/mg/diz.html)
else
    LD_LIBRARY_PATH="" xdg-open $(libtbx.find_in_repositories dlstbx/scratch/mg/diz.html)
fi
